- name: create crontab for project user
  template:
    src: templates/crontab.j2
    dest: /var/spool/cron/crontabs/{{ project_user }}
    mode: 0600
    owner: '{{ project_user }}'
    group: crontab
  notify: restart cron

- name: create crontab for certbot
  template:
    src: templates/certbot.j2
    dest: /etc/cron.d/certbot
    mode: 0600
    owner: root
    group: crontab
  notify: restart cron

